---
name: Download Artifact
description: Download artifact from the same or different workflow

inputs:
    name:
        description: Artifact to be downloaded
        required: true
        type: string

runs:
    using: composite
    steps:
      - name: Download Artifact
        uses: actions/github-script@v6
        with:
          script: |
            var inputs = ${{ toJSON(inputs) }}
            var artifactName = inputs['name']
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == artifactName
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/${artifactName}.zip`, Buffer.from(download.data));

      - name: 'Unzip artifact'
        run: unzip ${{ inputs.name }}.zip
        shell: bash
