name: Algorithm

on:
  push:
    branches:
      - 'main'
      - 'analysis/**'
      - 'test-docs'

jobs:
  algorithms:
    runs-on: ubuntu-latest
    outputs: # here we use the outputs from steps, and set outputs for the job `configure`
      algorithms: ${{ steps.algorithms.outputs.algorithms }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Cache pip
        uses: actions/cache@v3
        id: pip-cache
        with:
          key: ${{ runner.os }}-${{ env.pythonLocation }}-pip-${{ hashFiles('**/requirements.txt') }}
          path: ${{ env.pythonLocation }}
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Read algorithms
        id: algorithms
        run: |
          echo 'algorithms<<EOF' >> $GITHUB_OUTPUT
          cat ./tests/IVIMmodels/unit_tests/algorithms.json >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Log algorithms
        run: |
          echo "${{fromJson(steps.algorithms.outputs.algorithms)}}"
          echo "${{fromJson(steps.algorithms.outputs.algorithms).algorithms}}"
      - name: Log algorithms file
        run: cat ./tests/IVIMmodels/unit_tests/algorithms.json

