name: Build and Run Docker

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, edited]
    branches:
      - main
      - "docker/**"

jobs:
  build-and-run-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t tf2.4_ivim-mri_codecollection -f Docker/Dockerfile .

      - name: Save and compress Docker image 
        run: |
          docker save tf2.4_ivim-mri_codecollection | gzip > tf2.4_ivim-mri_codecollection.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: tf2.4_ivim-mri_codecollection.tar.gz

      - name: Run Docker container
        run: |
          docker run --rm --name TF2.4_IVIM-MRI_CodeCollection \
            -v ${{ github.workspace }}:/usr/src/app \
            -v ${{ github.workspace }}:/usr/app/output \
            tf2.4_ivim-mri_codecollection Docker/ivim_simulation.nii.gz Docker/ivim_simulation.bvec Docker/ivim_simulation.bval

      - name: Clean up artifacts and Docker image
        run: |
          docker rmi tf2.4_ivim-mri_codecollection || true
          rm -f tf2.4_ivim-mri_codecollection.tar.gz
          rm -f ${{ github.workspace }}/f.nii.gz
          rm -f ${{ github.workspace }}/dp.nii.gz
          rm -f ${{ github.workspace }}/d.nii.gz
